services:
  web:
    ports:
      - 127.0.0.1:8069:8069
      - 127.0.0.1:8071:8071
      - 127.0.0.1:8072:8072
    restart: unless-stopped
  db:
    ports:
      - 127.0.0.1:5232:5432
    restart: unless-stopped
